[application]
name = "puddle"
out_dir = "dist"
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "puddle"
base_path = "puddle"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["./tailwind.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
